services:
  database:
    restart: always
    image: mariadb:latest
    container_name: Database
    volumes:
      - database-data:/var/lib/mysql
      - database-config:/etc/mysql/conf.d
    environment:
      - MARIADB_ROOT_PASSWORD=abc
  server:
    container_name: REST-API
    build: .
    restart: always
    ports:
      - 5432:5432
    depends_on:
      database:
        condition: service_started
    environment:
      - JWT_TOKEN=yourSecretTokenWithSpecificLength
      - JWT_EXPIRE=8
      - DB_HOST=database
      - DB_PASSWORD=abc
    links:
      - database


volumes:
  database-config:
  database-data: